services:
  app:
    image: localhost:5000/api-tp13:1.0.0
    pull_policy: always
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:${PORT}/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3
      start_period: 15s

    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

